image: weltn24/up-docker-node-chrome-headless

stages:
  - test

test and lint:
  stage: test
  script:
    - npm i -g npm@latest
    - npm install
    - cd projects/angular2-jsonapi && npm install && cd ../..
    - npm test -- --no-watch --no-progress --code-coverage --browsers=ChromeHeadlessCI
    - npm run lint
