image: node:latest

stages:
  - test

test and lint:
  stage: test
  script:
    - npm i -g npm@latest
    - npm ci
    - cd projects/angular2-jsonapi && npm ci && cd ../..
    - npm test -- --no-watch --no-progress --code-coverage --browsers=ChromeHeadlessCI
    - npm run lint
